package.json
web/components.json
web/config/tailwind.config.js
web/package.json
web/src/components/ui/button.tsx
web/src/components/ui/calendar.tsx
web/src/components/ui/tooltip.tsx
web/src/index.css
web/src/lib/utils.ts
yarn.lock

Shadcn installation

---

web/config/tailwind.config.js
web/src/index.css

This PR swaps Shadcn default colors with Alluca custom colors.

Set alluca colors

---

package.json
yarn.lock

This PR install Storybook via `yarn rw storybook`

Install Storybook

---

web/package.json
web/src/components/ui/form.tsx
web/src/components/ui/input.tsx
web/src/components/ui/label.tsx
web/src/components/ui/textarea.tsx
web/src/pages/HomePage/HomePage.tsx
web/src/scaffold.css
yarn.lock

This PR applies changes to the root page. Fixes #15

Refining root page

---

web/src/components/RatingStars/RatingStars.stories.tsx
web/src/components/RatingStars/RatingStars.test.tsx
web/src/components/RatingStars/RatingStars.tsx

This PR adds a rating stars component.
Fixes #20

Add rating stars component

---

web/src/components/ui/button.tsx
web/src/components/ui/navigation-menu.tsx
web/src/index.css
web/src/layouts/AppLayout/AppLayout.tsx
web/src/pages/JobProfilesPage/JobProfilesPage.tsx

This PR applies the styling for the job profile page. Fixes #24

Restyle job profile page

---

web/package.json
web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/RatingStars/RatingStars.tsx
web/src/components/ui/separator.tsx
web/src/components/ui/switch.tsx
web/src/index.css
web/src/scaffold.css
yarn.lock

This PR changes the layout of the add job profile modal. 
From this:
To this:
Fixes issue #23

Style the add job profile modal

---

web/src/Routes.tsx
web/src/layouts/AppLayout/AppLayout.tsx
web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
web/src/pages/HomePage/HomePage.tsx
web/src/pages/LoginPage/LoginPage.tsx
web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
web/src/pages/SignupPage/SignupPage.tsx

This PR redirects users after logging in & adds a function to log out to the logout button. 
Fixes #29

Redirecting users after logging in + log out function

---

scripts/seed.ts
scripts/utils/seedCertificates.ts
scripts/utils/seedJobProfiles.ts

This PR adds a seeding function to seed the fake job profile data for development and testing.
Fixes #31

Adding a seeding function for the job profile data

---

api/src/lib/auth.ts
web/package.json
web/src/components/ui/dropdown-menu.tsx
web/src/components/ui/navigation-menu.tsx
web/src/layouts/AppLayout/AppLayout.tsx
yarn.lock

This PR changes the user profile menu to a dropdown menu. Fixes issue #28.
https://github.com/user-attachments/assets/7f4ba414-f56e-48ba-a3e4-72c44adfb6dc

Restyle profile dropdown menu

---

api/db/migrations/20240810145501_add_work_request_status/migration.sql
api/db/schema.prisma

This PR adds statuses to WorkRequest model to track the status of the request. 
Fixes #36

Add statuses to WorkRequest model

---

web/src/components/JobProfilesCell/JobProfilesCell.mock.ts
web/src/components/JobProfilesCell/JobProfilesCell.stories.tsx
web/src/components/JobProfilesCell/JobProfilesCell.test.tsx
web/src/components/JobProfilesCell/JobProfilesCell.tsx
web/src/components/RatingStars/RatingStars.tsx
web/src/components/ui/badge.tsx
web/src/components/ui/card.tsx
web/src/pages/JobProfilesPage/JobProfilesPage.tsx

This PR renders job profiles on the job profiles page. 
I'm not too sure about the design, and need help 🙏
@jazellemaira Could you take a stab at this? 🥺

Render Job Profiles on the job profiles page

---

web/src/components/ui/navigation-menu.tsx
web/src/layouts/AppLayout/AppLayout.tsx

This PR fixes all the links in the navigation menu that cause console errors. Fixes #41

Fix console errors

---

web/src/layouts/DefaultLayout/DefaultLayout.tsx
web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
web/src/pages/HomePage/HomePage.tsx
web/src/pages/LoginPage/LoginPage.tsx
web/src/pages/NotFoundPage/NotFoundPage.tsx
web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
web/src/pages/SignupPage/SignupPage.tsx
web/src/scaffold.css

This PR styles all the pages under the DefaultLayout set. 
Fixes #43 
From this:
To this:

Style the pages in DefaultLayout set

---

web/src/layouts/AppLayout/AppLayout.tsx

This PR fixes the re-rendering navigating between pages. 
I also changed the profile menu items to buttons.
Fixes #46

Fixing the re-rendering navigating between pages

---

web/src/components/AddJobProfileModal/AddJobProfileModal.tsx

This PR builds on @jazellemaira 's work, to make the validation process and feedback and coercion of responses better.
@jazellemaira let me know what you think!

Adding the validation process and error responses

---

web/src/components/AddJobProfileModal/AddJobProfileModal.tsx

This PR resolves the issue that an added profile does not appear immediately on the job profiles page.
Fixes #51

Added job profile will appear as soon as it's added

---

web/package.json
web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/ui/input.tsx
yarn.lock

This PR improves the AddJobProfileModal, including:
1. making optional fields optional consistent with the DB schema
2. adding the description to the dialog content to make it accessible
3. disabling the travel reimbursement field, when no reimbursement is available
4. hooking up the Switch component with appropriate values.
Fixes #57

Improving the AddJobProfileModal

---

web/src/components/BigCalendar/BigCalendar.tsx
web/src/components/BigCalendar/react-big-calendar.css

This PR restyles the big calendar component. Fixes #59 
https://github.com/user-attachments/assets/eb9fb388-e582-40ce-b473-a57fc790402d

Style the big calendar

---

web/src/layouts/AppLayout/AppLayout.tsx
web/src/pages/HomePage/HomePage.tsx

This PR adds a toast & loading spinner when logging in.
Fixes #69

Show a toast & loading spinner when logging in.

---

.vscode/settings.json

This PR adds the word "Alluca" to the workspace dictionary so that the spellchecker will not complain. 😊

Add "Alluca" to workspace dictionary

---

api/src/services/workRequests/workRequests.ts
web/src/components/OverviewSection/OverviewSection.stories.tsx
web/src/components/OverviewSection/OverviewSection.test.tsx
web/src/components/OverviewSection/OverviewSection.tsx
web/src/components/RequestStatusCard/RequestStatusCard.stories.tsx
web/src/components/RequestStatusCard/RequestStatusCard.test.tsx
web/src/components/RequestStatusCard/RequestStatusCard.tsx
web/src/components/WorkRequestsCell/WorkRequestsCell.mock.ts
web/src/components/WorkRequestsCell/WorkRequestsCell.stories.tsx
web/src/components/WorkRequestsCell/WorkRequestsCell.test.tsx
web/src/components/WorkRequestsCell/WorkRequestsCell.tsx
web/src/lib/formatAddress.ts
web/src/lib/formatToEuros.ts
web/src/pages/OverviewPage/OverviewPage.tsx

This PR renders work requests in the Overview Page.

Render work requests on the Overview Page

---

web/package.json
web/src/components/DrawerMenu/DrawerMenu.stories.tsx
web/src/components/DrawerMenu/DrawerMenu.test.tsx
web/src/components/DrawerMenu/DrawerMenu.tsx
web/src/components/ui/drawer.tsx
web/src/layouts/AppLayout/AppLayout.tsx
yarn.lock

This PR adds a drawer menu on mobile view.
https://github.com/user-attachments/assets/e71cae8c-fae4-41ed-809b-e19b161e60e6
Fixes #64

Add a drawer menu on mobile view

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx
web/src/components/ui/button.tsx
web/src/index.css
web/src/layouts/AppLayout/AppLayout.tsx

This PR adds minor changes to the job profile modal. Fixes #83

Styling add job profile modal

---

web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx
web/src/index.css
web/src/scaffold.css

This PR makes all the buttons and focus visibility consistent throughout the app. Fixes #85

Check button  and focus visibility consistency

---

web/src/components/JobProfilesCell/JobProfilesCell.mock.ts

Add mock data to JobProfilesCell for Storybook
Fixes #89

Add mock data to JobProfilesCell

---

web/src/components/JobProfilesCell/JobProfilesCell.tsx
web/src/components/ui/skeleton.tsx
web/src/pages/JobProfilesPage/JobProfilesPage.tsx

This PR creates JobProfilesCell skeleton. Fixes #81   
https://github.com/user-attachments/assets/863fe0f6-ae1f-4ac4-9abd-f6f737641470

 Loading skeleton: JobProfile

---

web/src/components/BigCalendar/react-big-calendar.css
web/src/components/WorkSchedularCell/WorkSchedularCell.tsx

This PR creates a loading state skeleton for the BigCalendar. Fixes #76 
https://github.com/user-attachments/assets/b6519af5-fa11-465a-a1ae-7136f3ed5502

BigCalendar loading skeleton

---

web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
web/src/pages/HomePage/HomePage.tsx
web/src/pages/LoginPage/LoginPage.tsx
web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
web/src/pages/SignupPage/SignupPage.tsx
web/src/scaffold.css

This PR changes the Redwood form colors to match the official logo.  Fixes #100

Recolor Redwood form

---

web/src/components/BigCalendar/react-big-calendar.css

This PR updates the colors of the Big Calendar to match the rest of the app. Fixes #102

Big Calendar recolor

---

web/config/tailwind.config.js
web/src/components/JobProfilesCell/JobProfilesCell.tsx

This PR removes named custom colors in tailwind config and JobProfileCell. Fixes #109

Remove named alluca custom colors

---

web/src/components/ConfirmDeleteWork/ConfirmDeleteWork.tsx
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx
web/src/components/ui/button.tsx

This PR improves the user feedback when creating a work request via using loading state.
https://github.com/user-attachments/assets/c1ef8a85-3a35-4db9-860f-0f6ba0e52148
Resolves #71

Improving user feedback when creating work request (loading state)

---

api/db/migrations/20240902162239_add_first_last_names/migration.sql
api/db/schema.prisma

This PR adds firstName and lastName fields to the User model in the DB schema. 
Resolves #106

Add firstName and lastName to the DB schema

---

api/db/migrations/20240904203147_agencies_have_shifts/migration.sql
api/db/schema.prisma
scripts/utils/seedShifts.ts

This PR connects agencies and shifts and add mock data for the association. 
Fixes #121

Connecting agencies and shifts

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR fixes the number of workers shown when editing a work request. Fixes #119 
https://github.com/user-attachments/assets/0dd5e377-ac74-453f-8019-e4d6dc0071fc

Fix the number of workers

---

.vscode/settings.json
LICENSE.md
README.md
web/src/components/DrawerMenu/DrawerMenu.tsx
web/src/layouts/AppLayout/AppLayout.tsx
web/src/pages/HomePage/HomePage.tsx
web/src/pages/NotFoundPage/NotFoundPage.tsx

This  PR replaces "Alluca" with the updated app name: "Fleckz" throughout the app. Fixes #126

Replace "Alluca" with "Fleckz"

---

web/src/components/AssignedShifts/AssignedShifts.stories.tsx
web/src/components/AssignedShifts/AssignedShifts.test.tsx
web/src/components/AssignedShifts/AssignedShifts.tsx
web/src/components/RequestStatusCard/RequestStatusCard.tsx

This PR refactors the assigned shifts section to a component. This renders assigned shifts specific only to requests that have assigned agencies. Fixes #136

Refactor assigned shifts section

---

package.json

This PR updates the shadcn CLI so that `yarn shad` works as expected.
Fixes #138

Update shadcn CLI

---

api/db/migrations/20240908145351_add_avatar_url/migration.sql
api/db/schema.prisma

This PR adds an avatarUrl to the User model, so that users can add their avatars. 
Resolves #147

Add avatarUrl to User model

---

web/src/components/Nav/Nav.tsx
web/src/layouts/AppLayout/AppLayout.tsx

This PR modifies the Nav component to allow style modifications when used on different pages. This also replaces the avatar fallback on the navigation bar. Fixes #150

Add classname to nav

---

web/src/components/SideNav/SideNav.tsx

This PR defines the prop type for className for the SideNav component. Fixes #154

Define prop type for className for SideNav

---

web/src/components/Nav/Nav.tsx

This PR defines prop types for className. Fixes #152

Define prop types for className Nav component

---

web/src/components/UpdateAccountCard/UpdateAccountCard.tsx
web/src/components/UpdateEmailCard/UpdateEmailCard.tsx
web/src/components/UpdatePasswordCard/UpdatePasswordCard.tsx

This PR moves all update buttons to the right end.  Fixes #161

Reposition update buttons

---

web/src/components/RequestStatusCard/RequestStatusCard.tsx

This PR fixes the overlapping of card title and status badge. Fixes #160 
https://github.com/user-attachments/assets/2f96c3d2-9f74-4538-bca4-dbe548486e38

Fix overlapping header elements - RequestStatusCard

---

web/src/components/OverviewSection/OverviewSection.tsx
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx
web/src/components/WorkRequestsCell/WorkRequestsCell.tsx

This PR creates additional categories for the work requests to correspond their status. Also, this PR adds a button to create a work request without leaving the page. Fixes #164 
https://github.com/user-attachments/assets/d9503b7c-9295-464c-bb60-96f2e1dac84d

Additional categories for overview

---

web/src/components/Nav/Nav.tsx

This PR show a tost after logging out.
https://github.com/user-attachments/assets/6cc2c4e8-d1be-45b1-8e3f-527241ece658
Fixes #75

Show a tost after logging out

---

web/src/components/ButtonWithLoader/ButtonWithLoader.stories.tsx
web/src/components/ButtonWithLoader/ButtonWithLoader.test.tsx
web/src/components/ButtonWithLoader/ButtonWithLoader.tsx
web/src/components/ConfirmAcceptWorkRequest/ConfirmAcceptWorkRequest.stories.tsx
web/src/components/ConfirmAcceptWorkRequest/ConfirmAcceptWorkRequest.test.tsx
web/src/components/ConfirmAcceptWorkRequest/ConfirmAcceptWorkRequest.tsx
web/src/components/ConfirmCompleteWorkRequest/ConfirmCompleteWorkRequest.stories.tsx
web/src/components/ConfirmCompleteWorkRequest/ConfirmCompleteWorkRequest.test.tsx
web/src/components/ConfirmCompleteWorkRequest/ConfirmCompleteWorkRequest.tsx
web/src/components/ConfirmDeleteWork/ConfirmDeleteWork.tsx
web/src/components/ConfirmRevertInProgress/ConfirmRevertInProgress.stories.tsx
web/src/components/ConfirmRevertInProgress/ConfirmRevertInProgress.test.tsx
web/src/components/ConfirmRevertInProgress/ConfirmRevertInProgress.tsx
web/src/components/ConfirmRevertToConfirmed/ConfirmRevertToConfirmed.stories.tsx
web/src/components/ConfirmRevertToConfirmed/ConfirmRevertToConfirmed.test.tsx
web/src/components/ConfirmRevertToConfirmed/ConfirmRevertToConfirmed.tsx
web/src/components/IndividualWorkRequestActions/IndividualWorkRequestActions.stories.tsx
web/src/components/IndividualWorkRequestActions/IndividualWorkRequestActions.test.tsx
web/src/components/IndividualWorkRequestActions/IndividualWorkRequestActions.tsx
web/src/components/WorkRequestCell/WorkRequestCell.tsx
web/src/components/WorkRequestCommentSection/WorkRequestCommentSection.tsx

This PR makes it possible to confirm the request and move statuses back and forth.
Fixes #67

Making it possible to confirm the request & move status back and forth

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

While I was working on 185, I saw some code needs clean-up. And thus I'm opening this PR.

Cleaning up PlanWorkComponent

---

web/src/components/IndividualWorkRequestActions/IndividualWorkRequestActions.tsx
web/src/components/JobProfileDetailsTable/JobProfileDetailsTable.tsx
web/src/components/WorkRequestCell/WorkRequestCell.tsx

This PR fixes the positioning of elements inside the individual work request page. Fixes #181 
Uploading Individual Request Card.mov…

Individual work request page layout

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR adds a save as draft button for the work request form. Also, this PR translates the update button to Dutch. Fixes #185

PlanWorkComponent buttons (Draft Button)

---

web/src/components/UpdateBusinessCard/UpdateBusinessCard.tsx

This PR adds a delete button for an existing business. Fixes #187

Add delete button for a business

---

api/db/migrations/20240912193106_add_business_and_workplace/migration.sql
api/db/schema.prisma

This PR adds client business and workplace model to the database.
Fixes #87

Add ClientBusiness and Workplaces Model

---

api/src/graphql/workRequests.sdl.ts
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR adds a user when creating a Work Request.
Fixes #197

Add userId when creating a workRequest

---

api/src/services/workRequests/workRequests.ts
web/src/components/WorkRequestCell/WorkRequestCell.tsx
web/src/lib/formatDateTime.ts

This PR adds rendering work request creator.

Rendering work request creator. 

---

api/src/lib/auth.ts
web/src/components/AssignedShifts/AssignedShifts.tsx
web/src/components/RequestStatusCard/RequestStatusCard.tsx

This PR adds an edit button on the request status cards. Fixes #200

Adding edit button on request status cards

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR adds a WorkRequestsCell query to initiate refetch when saving changes to the requests status cards. Fixes #202

Refetching issue work request card

---

api/db/migrations/20240913190203_cascade_delete_workplace/migration.sql
api/db/schema.prisma

This PR adds a database logic to cascade-delete any associated workplaces when deleting a business.

Cascade-delete workplace when deleting business

---

web/src/pages/OverviewPage/OverviewPage.tsx

This PR reduces the max width of the overview page to be consistent with other pages.

Overview max width

---

api/src/graphql/comments.sdl.ts
api/src/graphql/users.sdl.ts
api/src/graphql/workRequests.sdl.ts
api/src/services/comments/comments.scenarios.ts
api/src/services/comments/comments.test.ts
api/src/services/comments/comments.ts
api/src/services/workRequests/workRequests.ts
web/src/components/CommentSpeechBubble/CommentSpeechBubble.stories.tsx
web/src/components/CommentSpeechBubble/CommentSpeechBubble.test.tsx
web/src/components/CommentSpeechBubble/CommentSpeechBubble.tsx
web/src/components/WorkRequestCell/WorkRequestCell.tsx
web/src/components/WorkRequestCommentSection/WorkRequestCommentSection.tsx

This PR adds the functionality to add comments on WorkRequests.
Resolves #210

Commenting on WorkRequests

---

web/package.json
web/src/Routes.tsx
web/src/components/DrawerMenu/DrawerMenu.tsx
web/src/components/Nav/Nav.tsx
web/src/pages/DashboardPage/DashboardPage.stories.tsx
web/src/pages/DashboardPage/DashboardPage.test.tsx
web/src/pages/DashboardPage/DashboardPage.tsx
yarn.lock

This PR creates a mock dashboard page with mock data. Only for presentation purposes.
The data here does not correspond with the data from the database.

Mock Dashboard page

---

api/db/migrations/20241005094935_add_mediator_role/migration.sql
api/db/schema.prisma

This PR adds the Mediator role to the db schema.
Fixes #217

feat(db): Add mediator role to the db schema

---

web/src/components/OverviewCardsSkeleton/OverviewCardsSkeleton.stories.tsx
web/src/components/OverviewCardsSkeleton/OverviewCardsSkeleton.test.tsx
web/src/components/OverviewCardsSkeleton/OverviewCardsSkeleton.tsx
web/src/components/TableSkeleton/TableSkeleton.stories.tsx
web/src/components/TableSkeleton/TableSkeleton.test.tsx
web/src/components/TableSkeleton/TableSkeleton.tsx
web/src/components/WorkRequestsCell/WorkRequestsCell.tsx

This PR adds loading skeletons to the overview page. I also refactored the skeletons for Overview Cards.

Add loading skeletons

---

web/.storybook/preview.ts

This PR adds background colors to Storybook to improve developer (our) experience! 🙌
Resolves #241

feat(storybook): Add background colors to Storybook

---

web/package.json
web/src/components/SortButton/SortButton.stories.tsx
web/src/components/SortButton/SortButton.test.tsx
web/src/components/SortButton/SortButton.tsx
web/src/components/ui/select.tsx
yarn.lock

This PR creates a UI component for a sort button. Fixes #235 
Needs hooking up @nsunami  🙏🏽

Create abutton UI component for sort button

---

web/src/index.css

This PR fixes the rounding of buttons when on focus. Fixes #246

Remove the rounding of borders for buttons on focus

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR solves the issue #192 where all the buttons are showing loading spinners.
Resolves #192

Loading spinners appear only for the action performed

---

api/db/migrations/20241007185548_add_temp_agent_role/migration.sql
api/db/schema.prisma

This PR adds a temp agency representative role as our user.
Fixes #232 
Doing a PR to the existing DB change branch.

Add temp agency representative as a role [skip ci]

---

api/src/graphql/shifts.sdl.ts
api/src/services/shifts/shifts.ts
api/src/services/workRequests/workRequests.ts
web/src/components/CheckInTab/CheckInTab.stories.tsx
web/src/components/CheckInTab/CheckInTab.test.tsx
web/src/components/CheckInTab/CheckInTab.tsx
web/src/components/CheckOutTab/CheckOutTab.stories.tsx
web/src/components/CheckOutTab/CheckOutTab.test.tsx
web/src/components/CheckOutTab/CheckOutTab.tsx
web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.stories.tsx
web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.tsx
web/src/components/ShiftSummaryTab/ShiftSummaryTab.stories.tsx
web/src/components/ShiftSummaryTab/ShiftSummaryTab.test.tsx
web/src/components/ShiftSummaryTab/ShiftSummaryTab.tsx
web/src/components/ShiftTable/ShiftTable.tsx
web/src/components/ShiftTableCell/ShiftTableCell.tsx
web/src/components/TimePicker/TimePicker.stories.tsx
web/src/components/TimePicker/TimePicker.test.tsx
web/src/components/TimePicker/TimePicker.tsx
web/src/components/WorkRequestCell/WorkRequestCell.mock.ts
web/src/components/WorkRequestCell/WorkRequestCell.test.tsx
web/src/components/WorkRequestCell/WorkRequestCell.tsx
web/src/lib/formatInterval.test.ts
web/src/lib/formatInterval.ts

This PR adds the check-in and check-in functionality building on the frontend work by @jazellemaira 
(In retrospect, I should have separated this PR into smaller chunks...)
Resolves #269

Check-in and Check-out functionality

---

web/src/Routes.tsx
web/src/components/DrawerMenu/DrawerMenu.tsx
web/src/components/Nav/Nav.tsx
web/src/pages/TodayPage/TodayPage.stories.tsx
web/src/pages/TodayPage/TodayPage.test.tsx
web/src/pages/TodayPage/TodayPage.tsx

This PR creates the Today Page UI for the clients' side. Fixes #275 and #216

📆  Today page mobile

---

web/src/components/DrawerMenu/DrawerMenu.tsx
web/src/components/ui/drawer.tsx

This PR updates the look of the DrawerMenu. Fixes #279 
https://github.com/user-attachments/assets/d22c3e7e-a34a-457a-aeab-7e8d4d80965e

Improving DrawerMenu UI

---

web/src/components/AddJobProfileModal/AddJobProfileModal.tsx

This PR fixes the positioning of buttons on the AddJobProfileModal dialog. This PR also makes the buttons more distinguishable from each other. Fixes #295

Fixing AddJobProfileModal

---

api/src/graphql/workRequests.sdl.ts
api/src/services/workRequests/workRequests.ts
web/src/components/CheckOutTab/CheckOutTab.tsx
web/src/components/IndividualWorkRequestSection/IndividualWorkRequestSection.stories.tsx
web/src/components/IndividualWorkRequestSection/IndividualWorkRequestSection.test.tsx
web/src/components/IndividualWorkRequestSection/IndividualWorkRequestSection.tsx
web/src/components/SearchInput/SearchInput.tsx
web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.tsx
web/src/components/ShiftSummaryTab/ShiftSummaryTab.tsx
web/src/components/TempAgencyWorker/TempAgencyWorker.tsx
web/src/components/TodayShiftsTable/TodayShiftsTable.stories.tsx
web/src/components/TodayShiftsTable/TodayShiftsTable.test.tsx
web/src/components/TodayShiftsTable/TodayShiftsTable.tsx
web/src/components/WorkRequestsTodayCell/WorkRequestsTodayCell.mock.ts
web/src/components/WorkRequestsTodayCell/WorkRequestsTodayCell.stories.tsx
web/src/components/WorkRequestsTodayCell/WorkRequestsTodayCell.test.tsx
web/src/components/WorkRequestsTodayCell/WorkRequestsTodayCell.tsx
web/src/pages/TodayPage/TodayPage.tsx

This PR makes it possible to check in and out from the today page.
I did not implement the sort and filter function. Also, we have checkboxes, but we can't check in multiple people at the same time. 
Resolves #281

Today page with check-in buttons

---

web/src/components/ShiftTable/ShiftTable.tsx
web/src/components/WorkRequestCell/WorkRequestCell.tsx

This PR is a suggestion to the PR #308.
- Adding the start and end time to the top of the
- Removing the time column, since the time information is now rendered above the table

Adding the time to the title, and removing the time column

---

web/src/components/ShiftTable/ShiftTable.tsx
web/src/components/WorkRequestCell/WorkRequestCell.tsx

This PR adds the work request startDate on top of the ShiftTable. Also, this PR creates a placeholder for the shift time in the ShiftTable. 
@nsunami I need your help in getting the right values for the time column.

Adding startDate and shiftTime on the ShiftTable section

---

api/src/graphql/shifts.sdl.ts
web/src/components/AssignShiftWorkerDialog/AssignShiftWorkerDialog.stories.tsx
web/src/components/AssignShiftWorkerDialog/AssignShiftWorkerDialog.test.tsx
web/src/components/AssignShiftWorkerDialog/AssignShiftWorkerDialog.tsx
web/src/components/ShiftTable/ShiftTable.tsx

This PR makes it possible to assign a worker to each shift. 
(I also want to add tests, but not with this PR—I will be working on building tests on another branch.)
Resolves #309

Assign worker to shifts

---

web/src/components/AddBusinessDialog/AddBusinessDialog.tsx
web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/AddTempAgencyDialog/AddTempAgencyDialog.tsx
web/src/components/AddWorkplaceDialog/AddWorkplaceDialog.tsx
web/src/components/AssignShiftWorkerDialog/AssignShiftWorkerDialog.tsx
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR changes the vertical overflow of dialogs from scroll to auto.  Fixes #317

Show scroll  bar on dialogs only when needed

---

web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
web/src/pages/HomePage/HomePage.tsx
web/src/pages/LoginPage/LoginPage.tsx
web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
web/src/pages/SignupPage/SignupPage.tsx

This PR redirects authenticated users to the today (vandaag) page by default.
Resolves #324

Navigate authenticated users to today by default

---

web/src/components/Nav/Nav.tsx

Clicking the logo will link out to the Today page (not the Overview page).

feat(Nav): Click logo to navigate to Today [skip ci]

---

web/package.json
web/src/components/AssignShiftWorkerDialog/AssignShiftWorkerDialog.test.tsx
yarn.lock

This PR adds a test for worker dialogue component.
PR to #319 because the tests are depended on the components created in PR #319. 
Resolves #320

Add a test worker dialogue [skip ci]

---

web/src/components/ShiftTable/ShiftTable.tsx
web/src/lib/formatShiftId.test.ts
web/src/lib/formatShiftId.ts

This PR renders the last 6 letters of Shift ID in Shift Table. 
Resolves #327.

Render the last 6 letters of the Shift ID in Shift Table 

---

api/src/services/users/users.test.ts
api/src/services/users/users.ts

This PR makes it possible for admins to edit and delete other people's accounts
Fixes #345

Admins can edit and delete other accounts

---

web/src/components/WorkRequestsCell/WorkRequestsCell.tsx

This PR shows the table view as the default view on the Overview page.
Fixes #353

feat(overview): Show table view as the default view

---

web/src/index.css

This PR tweaks the secondary custom color to match the brand feel and colors better.  Fixes #358

Adjust secondary custom color

---

api/db/migrations/20241121202647_invoices_and_bonuses/migration.sql
api/db/schema.prisma

This PR adds the database models for invoices and bonuses (toeslagen)
After merging, we need to run `yarn rw prisma migrate dev`

feat(db): Add bonus and invoice model

---

api/src/lib/fakeData/createFakeUsers.test.ts
api/src/lib/fakeData/createFakeUsers.ts
scripts/seedFakeData.ts

This PR adds a mocking for fake users via faker-js (Clients and Temp Agency Representatives)
Fixes #368 
Merging into #367

Mock users using faker-js

---

api/db/migrations/20241123202230_worker_and_skill/migration.sql
api/db/schema.prisma

This PR adds Worker and invoice models. 
I realize we need to:
Fixes #363

feat(db): Add worker and skill models

---

web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR stores the onboarding state in the URL parameter. Such as:
```
.../onboarding?stage=selectRole
```

feat(onboarding): Store the onboarding state in the URL params

---

web/src/components/OnboardingSelectRole/OnboardingSelectRole.tsx
web/src/components/SelectBusiness/SelectBusiness.stories.tsx
web/src/components/SelectBusiness/SelectBusiness.test.tsx
web/src/components/SelectBusiness/SelectBusiness.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds a component to select a business to the onboarding UI:
https://github.com/user-attachments/assets/2418942d-3d10-4049-86fc-fb8e5361ecff
Fixes #374

Add select business component to onboarding

---

web/src/components/OnboardingInternalOrganization/OnboardingInternalOrganization.stories.tsx
web/src/components/OnboardingInternalOrganization/OnboardingInternalOrganization.test.tsx
web/src/components/OnboardingInternalOrganization/OnboardingInternalOrganization.tsx
web/src/components/SelectBusiness/SelectBusiness.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the internal organization page (component) for the onboarding process.
Fixes #383 
https://github.com/user-attachments/assets/102b9734-4013-4d1f-9e43-509e4aa45d4a

Add the internal organization page for onbording 

---

web/src/components/AddAuthorizedSignatory/AddAuthorizedSignatory.stories.tsx
web/src/components/AddAuthorizedSignatory/AddAuthorizedSignatory.test.tsx
web/src/components/AddAuthorizedSignatory/AddAuthorizedSignatory.tsx
web/src/components/SelectBusiness/SelectBusiness.tsx
web/src/components/TextInput/TextInput.stories.tsx
web/src/components/TextInput/TextInput.test.tsx
web/src/components/TextInput/TextInput.tsx
web/src/components/ui/label.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the authorized signatory page (component)  and text input (component) for the onboarding process.
Fix #380 
https://github.com/user-attachments/assets/b0a8c1b4-a368-404c-9f57-3bfa46b8d495

Add authorized signatory page

---

web/src/components/AddAuthorizedSignatory/AddAuthorizedSignatory.tsx
web/src/components/OnboardingFinancial/OnboardingFinancial.stories.tsx
web/src/components/OnboardingFinancial/OnboardingFinancial.test.tsx
web/src/components/OnboardingFinancial/OnboardingFinancial.tsx
web/src/components/ui/input.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the Financial information page for the onboarding quest.
Fixes #381

Add Financial Component for the Onboarding Page

---

web/src/components/OnboardingInternalOrganization/OnboardingInternalOrganization.tsx
web/src/components/ui/label.tsx

This PR fixes a typo and styling of the internal organization page.
from this:
_______________________________________________________
to this:
https://github.com/user-attachments/assets/921b3dcb-16e9-4d08-b768-5b58fa319cfb
Fixes #391

Internal organization page

---

web/src/components/AddBranch/AddBranch.stories.tsx
web/src/components/AddBranch/AddBranch.test.tsx
web/src/components/AddBranch/AddBranch.tsx
web/src/components/OnboardingFinancial/OnboardingFinancial.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds a new component to add branch during onboarding:
Fixes #382

Onboarding: Add addBranch component

---

api/db/migrations/20250102135139_make_billing_address_nullable/migration.sql
api/db/schema.prisma

This PR fixes the issue of unable to add a business, by allowing the billing address nullable. 
Fixes #409 
Please run `yarn rw prisma migrate dev`

fix(ClientBusiness): Make the billing address nullable

---

web/src/components/OnboardingAddJobProfile/OnboardingAddJobProfile.tsx
web/src/components/OnboardingPlanWork/OnboardingPlanWork.stories.tsx
web/src/components/OnboardingPlanWork/OnboardingPlanWork.test.tsx
web/src/components/OnboardingPlanWork/OnboardingPlanWork.tsx
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx
web/src/components/ui/input.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the component for planning a work during the onboarding view.
Fixes #402 
The path to the work is:
/onboarding?stage=planWork

Onboarding: Plan Work View

---

web/src/components/OnboardingEmailAndPassword/OnboardingEmailAndPassword.tsx

This PR skips validation for email and password during onboarding, for demo purposes.
Fixes #413

chore(OnBoardingEmailAndPassword): Skip validation

---

web/src/components/HireWorker/HireWorker.stories.tsx
web/src/components/HireWorker/HireWorker.test.tsx
web/src/components/HireWorker/HireWorker.tsx
web/src/components/OnboardingPlanWork/OnboardingPlanWork.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the list view to show candidate workers during the onboarding.
Fixes #395

Onboarding: List of candidate workers

---

web/src/components/HireWorker/HireWorker.tsx

This PR adds a view for selecting workers and getting a confirmation.
Fixes #396

Onboarding: Selecting workers and getting confirmation

---

web/src/components/ui/button.tsx

This PR tweaks button variants for better contrast and consistency. Fixes #434 
https://github.com/user-attachments/assets/7b7d8905-eca5-4eb8-83d7-e67ecc2be7db

Button variants

---

web/src/components/OnboardingFinancial/OnboardingFinancial.tsx

This PR tweaks the layout of the onboarding finance page to match the other pages. Fixes #443

Onboarding finance page layout mismatch

---

web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR saves the role data in the URL param.
Fixes #450

feat(Onboarding): Save role as a URL param

---

web/src/components/SelectBusiness/SelectBusiness.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds a select business view for the UZB. I'm prop drilling the role to the child components.

feat(Onboarding): Select business for UZB

---

web/src/components/AddAuthorizedSignatory/AddAuthorizedSignatory.tsx
web/src/components/AddBranch/AddBranch.tsx
web/src/components/HireWorker/HireWorker.tsx
web/src/components/OnboardingAddJobProfile/OnboardingAddJobProfile.tsx
web/src/components/OnboardingAvatarAndName/OnboardingAvatarAndName.tsx
web/src/components/OnboardingContactPerson/OnboardingContactPerson.tsx
web/src/components/OnboardingEmailAndPassword/OnboardingEmailAndPassword.tsx
web/src/components/OnboardingFinancial/OnboardingFinancial.tsx
web/src/components/OnboardingInternalOrganization/OnboardingInternalOrganization.tsx
web/src/components/OnboardingPlanWork/OnboardingPlanWork.tsx
web/src/components/OnboardingSelectRole/OnboardingSelectRole.tsx
web/src/components/OnboardingSuccess/OnboardingSuccess.tsx
web/src/components/OnboardingWelcomeMessage/OnboardingWelcomeMessage.tsx
web/src/components/SelectBusiness/SelectBusiness.tsx
web/src/pages/OnboardingPage/OnboardingContext.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR applies the React context to avoid prop drilling, simplifying the code.
Fixes #453

Onboarding: Use react context to avoid prop drilling

---

web/src/components/AddAuthorizedSignatory/AddAuthorizedSignatory.tsx
web/src/components/AddBranch/AddBranch.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR shows the AddBranch view after asking for an authorized signatory for the UZB onboarding. 
Fixes #419

feat(UZB-Onboarding): Show AddBranch after AuthorizedSignatory

---

web/src/components/OnboardingFinancial/OnboardingFinancial.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR will show the financial info form after the branch form, before the contact person form. 
Fixes #420

feat(OnboardingUZB): Show Financial Info Form after Branch and before contact person form

---

web/src/components/OnboardingContactPerson/OnboardingContactPerson.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR shows the form for the contact person after the financial info form, before the certificate form.
Fixes #421

feat(OnboardingUZB): Show ContactPerson after Financial before Certificates

---

web/src/components/Certificates/Certificates.stories.tsx
web/src/components/Certificates/Certificates.test.tsx
web/src/components/Certificates/Certificates.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the certifications form for the UZB, for the onboarding.
Fixes #422

Onboarding for UZB: Add Certifications form

---

web/src/components/OnboardingInternalOrganization/OnboardingInternalOrganization.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the Internal Organization form after the Certifications form, before the Confirmation form.
Fixes #423

Onboarding UZB: Add the Internal Organization form after the Certifications form, before the Confirmation form

---

web/src/components/OnboardingConfirmInfo/OnboardingConfirmInfo.stories.tsx
web/src/components/OnboardingConfirmInfo/OnboardingConfirmInfo.test.tsx
web/src/components/OnboardingConfirmInfo/OnboardingConfirmInfo.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds a view to confirm information during the onboarding process for the UZB.
Fixes #424

Onboarding UZB: Add a view to confirm the information

---

web/src/components/WorkerInfoCard/WorkerInfoCard.stories.tsx
web/src/components/WorkerInfoCard/WorkerInfoCard.test.tsx
web/src/components/WorkerInfoCard/WorkerInfoCard.tsx

This PR introduces the WorkerInfo and WorkerInfoCard components, adding detailed worker information display and improved skill selection functionality with popover and badge features. Fixes #427

Add WorkerInfo and WorkerInfoCard components with enhanced features

---

web/src/components/ChooseSoftSkills/ChooseSoftSkills.tsx
web/src/components/OnboardingAddJobProfile/OnboardingAddJobProfile.tsx

Restore the soft skills label in the onboarding form to enhance user experience and clarity. Fixes #464

Reintroduce soft skills label in onboarding form

---

web/src/components/CvsList/CvsList.stories.tsx
web/src/components/CvsList/CvsList.test.tsx
web/src/components/CvsList/CvsList.tsx
web/src/components/WorkerInfoCard/WorkerInfoCard.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR shows CVsList and shows after the CV uploading page.
Fixes #427

Add CvsList component and integrate it into the OnboardingPage

---

web/src/components/ChooseSoftSkills/ChooseSoftSkills.tsx
web/src/components/CvsList/CvsList.tsx
web/src/components/EditWorkerInfo/EditWorkerInfo.stories.tsx
web/src/components/EditWorkerInfo/EditWorkerInfo.test.tsx
web/src/components/EditWorkerInfo/EditWorkerInfo.tsx
web/src/components/WorkerInfoCard/WorkerInfoCard.tsx

This PR adds the view to edti the worker information after uploading CVs during UZB onboarding. 
Fixes #428

Onboarding UZB: Edit Worker Information View

---

web/src/Routes.tsx
web/src/components/CvsList/CvsList.tsx
web/src/components/DrawerMenu/DrawerMenu.tsx
web/src/components/Nav/Nav.tsx
web/src/pages/CandidatesPage/CandidatesPage.stories.tsx
web/src/pages/CandidatesPage/CandidatesPage.test.tsx
web/src/pages/CandidatesPage/CandidatesPage.tsx

This PR creates a separate candidates page. 
Fixes #431

Create a Candidates Page

---

web/src/components/DrawerMenu/DrawerMenu.tsx

This PR updates the drawer menu to the one on Canva. 
I also added a switch to show all the options.
Fixes #429

feat(DrawerMenu): Add show full menu switch

---

web/src/components/WorkRequestsList/WorkRequestsList.tsx
web/src/components/WorkRequestsListItem/WorkRequestsListItem.stories.tsx
web/src/components/WorkRequestsListItem/WorkRequestsListItem.test.tsx
web/src/components/WorkRequestsListItem/WorkRequestsListItem.tsx

This PR introduces the WorkRequestsListItem component for improved readability and maintainability in the WorkRequestsList. Adds corresponding stories and tests for the new component.

WorkRequestsListItem component
