scripts/seed.ts
scripts/seedFakeData.ts
scripts/utils/seedAddresses.ts
scripts/utils/seedCertificates.ts
scripts/utils/seedJobProfiles.ts

This PR generates fake addresses for development. I also moved the seeding script to `seeFakeData` to avoid seeding a production DB. (For the reasons described in [RedwoodDoc](https://docs.redwoodjs.com/docs/database-seeds) 🙏)

Generating fake addresses for development

---

web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR fixes the issue of inability to submit a work request with more than 1 worker. 
The PR coerces the number of worker field to be a value from a string.
Fixes #60

Fixing the issue of not being able to submit work request with more than 1 workers

---

web/src/layouts/AppLayout/AppLayout.tsx

This PR makes the menu item buttons full-width:
Before:
After:
Fixes #72

Making the menu item buttons full width

---

web/src/components/SelectAddressCell/SelectAddressCell.tsx
web/src/components/SelectJobProfileCell/SelectJobProfileCell.tsx

This PR creates a loading state skeleton for the combo boxes: SelectJobProfileCell and SelectAddressCell. Fixes #82.
Before:
https://github.com/user-attachments/assets/7882e031-e57e-4afa-9c4c-7f76f34f497f
After:
https://github.com/user-attachments/assets/212f2fe1-9236-48f1-b6df-8e3cb7785e99

Loading skeleton combo boxes

---

web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/JobProfileCard/JobProfileCard.tsx
web/src/components/JobProfilesCell/JobProfilesCell.tsx

This PR removes the RatingStars section in the JobProfileCard, AddJobProfileModal, and JobProfileCell. Fixes #120

Remove RatingStars

---

web/src/components/AssignedShifts/AssignedShifts.tsx

This PR resolves the bug where the number of workers rendered for each shift was based on the number of workers in the whole request.
Fixes #144

Fix the number of workers rendered for each shift

---

web/src/components/ShiftTable/ShiftTable.tsx

This PR fixes the bug where we could not change the agency assigned. 
Fixes #168

Bring back the id column & render empty fragment

---

api/db/migrations/20240912062634_add_hours_to_shifts/migration.sql
api/db/schema.prisma

This PR adds hoursPlanned and hoursWorked to the shifts.
Since this is a database change, we need to run `yarn rw prisma migrate dev` after merging these changes.
Fixes #131

Add hoursPlanned and hoursWorked to the shifts

---

web/src/components/JobProfileCard/JobProfileCard.tsx

This PR fixes the bug rendering '0' without labels when a value is not set. Fixes #176

Fix rendering job profile rendering '0' without context

---

api/src/services/workRequests/workRequests.ts

Now we can save our database. 
Fixes #194

Throw error when adding 100 workers or more to a work request

---

api/src/services/workRequests/workRequests.ts

This is to fix the bug introduced in #191 .

Error out when there are more shifts to remove than the number of unfulfilled shifts

---

api/db/migrations/20240913181650_make_province_optional/migration.sql
api/db/schema.prisma

This PR makes the province field of the address model optional.

Making the "province" field of the address optional

---

api/src/graphql/addresses.sdl.ts

We were having the issue of GraphQL expecting that the province is required, but the province field was nullable on the database.
This PR fixes the issue by making the GraphQL SDL file's definition of "province" nullable.

Make province as nullable in SDL

---

api/db/migrations/20240914142851_add_comment_model/migration.sql
api/db/schema.prisma

This PR adds comments model to the database schema.
After merging, we need to run `prisma migrate dev` ⭐️
Resolves #107

Add comments schema to the database model [skip ci]

---

api/src/services/jobProfiles/jobProfiles.ts
web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/ConfirmAction/ConfirmAction.stories.tsx
web/src/components/ConfirmAction/ConfirmAction.test.tsx
web/src/components/ConfirmAction/ConfirmAction.tsx
web/src/components/JobProfileCard/JobProfileCard.tsx

This PR makes it possible to edit job profiles. 
Two notes:
1. I created a new component for confirmation dialog (ConfirmActionComponent), which can be used for similar cases. 
2. The modal component accepts `trigger` prop, which is an element for the trigger. In other implementations, we use `isEditing` to conditionally render elements. I think this approach of using trigger is better because it's explicit and avoids conditionals. If so, we want to change the `isEditing` use in other places.

feat(jobProfile): Can edit job profiles

---

.vscode/settings.json

This PR is a suggestion to use non-relative import paths for modules. 
For example, instead of doing:
```ts
import { Button } from '../ui/button'
```
it will be:
```ts
import { Button } from 'src/components/ui/button'
```
@jazellemaira what do you think?

chore(vscode): Use non-relative import paths for modules

---

web/src/components/DiscardChangesAlert/DiscardChangesAlert.stories.tsx
web/src/components/DiscardChangesAlert/DiscardChangesAlert.test.tsx
web/src/components/DiscardChangesAlert/DiscardChangesAlert.tsx
web/src/components/PlanWorkComponent/PlanWorkComponent.tsx

This PR adds a confirmation dialogue to confirm discarding any edits (if the form is dirty). This is only for the Plan Work component.
Let's open issues for other dialogs, if needed...
Fixes #68

Show confirmation dialog to discard any edits

---

web/src/Routes.tsx
web/src/components/Nav/Nav.tsx
web/src/components/SideNav/SideNav.tsx
web/src/pages/TempAgenciesPage/TempAgenciesPage.tsx

This PR moves the uitzendbureau page to the settings set. 
We still don't have role-based access control yet, so the page is accessible by all the users. 
We need to restrict access to this page only for admins and intermediaries. I created an issue here to continue working on this:  https://github.com/fleckz-nl/fleckz/issues/262
Fixes #237

Moving the uitzendbureau page to the settings

---

api/src/services/addresses/addresses.ts

This PR only shows addresses for the businesses created by the users (client).
This rule does not apply to admins and mediators. They still see all the addresses. 
Fixes #260

feat(address): Restrict address search to their own

---

api/package.json
package.json
web/package.json
yarn.lock

This PR upgrades RedwoodJS to 8.4.0.
Resolves #266

chore(rw): Upgrade to 8.4.0

---

web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.stories.tsx
web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.test.tsx
web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.tsx
web/src/components/TempAgencyWorker/TempAgencyWorker.stories.tsx
web/src/components/TempAgencyWorker/TempAgencyWorker.test.tsx
web/src/components/TempAgencyWorker/TempAgencyWorker.tsx
web/src/components/TimePicker/TimePicker.stories.tsx
web/src/components/TimePicker/TimePicker.test.tsx
web/src/components/TimePicker/TimePicker.tsx
web/src/components/ui/drawer.tsx

This PR creates a ShiftConfirmationDrawer UI component for the client side. FIxes #236 
We need to hook this up, ASAP @nsunami  🙏🏽 I created an issue for you here:  #269

Creating shift confirmation drawer

---

api/db/migrations/20241011200057_add_check_in_and_out/migration.sql
api/db/migrations/20241011200153_add_worker_name_to_shifts/migration.sql
api/db/schema.prisma

This PR updates the Shift model so that we can track check-in & check-out times, and the names of workers.
Resolves #273 
Since this PR changes the database schema, don't forget to run `prisma migrate dev` after merging.

🛢️ Update the Shift model to handle check-in, check-out, and names of wokeres [skip ci]

---

api/src/graphql/shifts.sdl.ts

This PR adds the CHECKED_IN and CHECKED_OUT enums introduced in the #40 to the GraphQL definitions (SDL). Without this the DB query was failing.

feat(ShiftStatus): Add checked-in and checked-out as shift statuses

---

web/src/components/DrawerMenu/DrawerMenu.tsx

This PR removes the Uitzendbureau from the DrawerMenu. Fixes #291

Remove the Uitzendbureau from the DrawerMenu

---

web/src/pages/HomePage/HomePage.tsx

This PR updates the login page tagline placeholder.  Fixes #297

Replace login page tagline

---

web/src/components/ShiftConfirmationDrawer/ShiftConfirmationDrawer.tsx

This PR adds the DrawerBar to the ShiftConfirmationDrawer content to indicate the direction the drawer opens from. Fixes #289

ShiftConfirmationDrawer update

---

web/src/pages/HomePage/HomePage.tsx

This PR changes the site tagline to "De zoekmachine voor uitzendkrachten". Fixes #325

Site tagline update

---

api/src/graphql/users.sdl.ts
api/src/services/users/users.scenarios.ts
api/src/services/users/users.test.ts

This PR fixes a bug where we cannot update the user info (Issue #333)
I made the GraphQL "role" input optional to fix this. 
Resolves #333

fix: Can update the user info again

---

web/src/components/AddJobProfileModal/AddJobProfileModal.tsx
web/src/components/ConfirmAction/ConfirmAction.test.tsx
web/src/components/ConfirmAction/ConfirmAction.tsx

This PR changes the API of the confirm action dialog component, so that the dialog trigger can be any element other than a button.
I wanted this when working on #306, where the Trash can icon is styled not red.

Change the api of the confirm action component [skip ci]

---

web/src/components/UpdateBusinessCard/UpdateBusinessCard.test.tsx
web/src/components/UpdateBusinessCard/UpdateBusinessCard.tsx

This PR adds a confirmation dialog before deleting a business.
This change is dependent on the change on PR #343.
Resolves #306

Confirm before deleting a business

---

web/src/components/IndividualWorkRequestSection/IndividualWorkRequestSection.test.tsx
web/src/components/IndividualWorkRequestSection/IndividualWorkRequestSection.tsx

This PR renders the project name to the individual work requests on the Today Page, and places a link to the corresponding work request page.
Resolves #332

Render the project name to individual work requests on Today Page, and link out to a corresponding Work Request Page

---

api/src/graphql/workRequests.sdl.ts
api/src/services/workRequests/workRequests.ts
web/src/components/WorkRequestsTodayCell/WorkRequestsTodayCell.tsx
web/src/lib/formatters.test.tsx
web/src/lib/formatters.tsx
web/src/pages/TodayPage/TodayPage.tsx

This PR adds navigation arrows to move between dates on the Today page.
Fixes #349

Add navigation arrows on Today page to move between dates

---

api/db/migrations/20241112190430_link_users_with_temp_agency/migration.sql
api/db/schema.prisma

This PR adds members to the temp agency schema so that temp agency reps will be linked to temp agencies.
After merging this, we need to run migrations `yarn rw prisma migrate dev`
Fixes #351

🛢️feat(db): Add members to temp agency

---

api/src/services/workRequests/workRequests.ts

This PR restricts updating and editing work requests to admins and clients. (so that temp agency reps won't be able to edit things).
This PR only includes backend codes. UI also needs to be changed so that users won't see functionalities there. 
Fixes #225

feat(workRequests): Only admin or client can update & delete requests

---

web/src/components/ShiftTable/ShiftTable.tsx

This PR removes the ability for clients and temp agency representatives to select or change TempAgency.  Fixes #348

Show SelectAgency combo box only to admin

---

web/src/components/IndividualWorkRequestSection/IndividualWorkRequestSection.tsx
web/src/components/ShiftStatusBadge/ShiftStatusBadge.stories.tsx
web/src/components/ShiftStatusBadge/ShiftStatusBadge.test.tsx
web/src/components/ShiftStatusBadge/ShiftStatusBadge.tsx

This PR renders a badge to indicate the shift status in TodayPage. Fixes #361

Shift status indicator

---

web/config/tailwind.config.js

This PR makes the custom border radius styling work correctly again. Fixes #375

Border radius issue

---

web/src/components/TempAgencyWorker/TempAgencyWorker.tsx

This PR adds a placeholder for workers' photo for the TodayShiftTable. 
Fixes #405

Today Page - TemAgencyWorker component

---

web/src/components/HireWorker/HireWorker.tsx

This PR replaces the next button on the last onboarding stage with a finish button that navigates to the overview page.  Fixes #445

Finish button - Onboarding last stage

---

web/src/components/OnboardingAddJobProfile/OnboardingAddJobProfile.tsx

This PR restyles the CTA button on the add job profile onboarding step to match the one used on the JobProfile page. Fixes #447

 Onboarding - add job profile step

---

web/src/components/CvUpload/CvUpload.stories.tsx
web/src/components/CvUpload/CvUpload.test.tsx
web/src/components/CvUpload/CvUpload.tsx
web/src/pages/OnboardingPage/OnboardingPage.tsx

This PR adds the CV upload view during the UZB onboarding, to be shown after the success message, and before the CV list. 
Fixes #426

Onboarding UZB: Add the CV Upload view

---

web/src/components/HireWorker/HireWorker.tsx

This PR will show "Pay now" button after finding matches with the workers, at the end of the onboarding for clients. 
Fixes #474

feat(HireWorker): Encourage paying now after finding matches

---

web/src/Routes.tsx
web/src/components/WorkRequestsListItem/WorkRequestsListItem.tsx
web/src/pages/ConfirmWorkRequestPage/ConfirmWorkRequestPage.stories.tsx
web/src/pages/ConfirmWorkRequestPage/ConfirmWorkRequestPage.test.tsx
web/src/pages/ConfirmWorkRequestPage/ConfirmWorkRequestPage.tsx

This PR introduces a new page for confirming work requests with improved routing and layout. Enhances item click handling in the work requests list to support navigation to the confirmation page.
Fixes #478

Add Confirm Work Request page and enhance item handling

---

web/src/components/DrawerMenu/DrawerMenu.tsx

This PR refactors the DrawerMenu component to toggle the UZB menu and updates the navigation links to reflect the new structure. Fixes #480

Update DrawerMenu to show UZB menu and adjust links accordingly
